# Generated by Django 5.1 on 2024-08-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('price', models.FloatField(default=0.0, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='plates', verbose_name='Imagen')),
                ('category', models.ManyToManyField(related_name='category', to='categories.categories')),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='ingredients.ingredients')),
            ],
            options={
                'verbose_name': 'Plate',
                'verbose_name_plural': 'Plates',
            },
        ),
    ]
