# Generated by Django 5.1 on 2024-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plates',
            name='image',
            field=models.ImageField(upload_to='plates/', verbose_name='Imagen'),
        ),
    ]
