# Generated by Django 5.1 on 2024-09-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_alter_plates_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
