# Generated by Django 5.1.1 on 2024-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Precio')),
                ('size', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tamaño')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('image', models.ImageField(upload_to='drinks/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Drink',
                'verbose_name_plural': 'Drinks',
            },
        ),
    ]
