# Generated by Django 5.1 on 2024-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(upload_to='drinks/', verbose_name='Imagen'),
        ),
    ]
